# -*- coding: utf-8 -*-
"""lab1.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TaxpbW47oAnGPrGyl_pYYf87O_C0TC_t
"""

# Commented out IPython magic to ensure Python compatibility.
import cv2
import numpy as np
from matplotlib import pyplot as plt
from PIL import Image
# %matplotlib inline
from google.colab.patches import cv2_imshow
import matplotlib.image as mpimg
from mpl_toolkits.mplot3d.axes3d import math
img=cv2.imread("/content/suga-agust-d-bts-hd-wallpaper-preview.jpg")

#1.1.1

fig=plt.figure(figsize=(12,12))

b=img[:,:,0]
g=img[:,:,1]
r=img[:,:,2]
fig.add_subplot(1,4,1)
plt.imshow(img,cmap='gray')
fig.add_subplot(1,4,2)
plt.imshow(b,cmap='gray')
fig.add_subplot(1,4,3)
plt.imshow(g,cmap='gray')
fig.add_subplot(1,4,4)
plt.imshow(r,cmap='gray')

img2=img.copy()
img2=img[:,:,::-1]
r=img2[:,:,0]
g=img2[:,:,1]
b=img2[:,:,2]
fig.add_subplot(2,4,5)
plt.imshow(img2,cmap='gray')
fig.add_subplot(2,4,6)
plt.imshow(r,cmap='gray')
fig.add_subplot(2,4,7)
plt.imshow(g,cmap='gray')
fig.add_subplot(2,4,8)
plt.imshow(b,cmap='gray')

print(img.shape)

imgt=np.transpose(img)
print('Transpose',imgt.shape)
imgm=np.moveaxis(img,2,0)
print('Moveaxis',imgm.shape)
imgr=np.reshape(img,(3,485,728))
print('Reshape',imgr.shape)

#1.1.2
fig=plt.figure(figsize=(12,12))

fig.add_subplot(2,4,1)
plt.imshow(b,cmap='gray')
plt.title('R_Original')
fig.add_subplot(2,4,2)
plt.imshow(imgt[0],cmap='gray')
plt.title("R_Transpose")
fig.add_subplot(2,4,3)
plt.imshow(imgm[0],cmap='gray')
plt.title('R_Moveaxis')
fig.add_subplot(2,4,4)
plt.imshow(imgr[0],cmap='gray')
plt.title('R_Reshape')

#1.1.3

fig=plt.figure(figsize=(15,12))
if img.ndim==3:
    gray_img = cv2.cvtColor(img,cv2.COLOR_RGB2GRAY)
    plt.subplot(1, 2, 1).imshow(gray_img, cmap="gray")
result=np.floor((gray_img/255)*2**2)
plt.subplot(1, 2, 2).imshow(result, cmap="gray")
plt.show()

#1.1.4
image_path= gray_img
image_array = np.array(image_path)
x,y = np.mgrid[0:image_array.shape[0],0:image_array.shape[1]]
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d') #integers (rows, columns, index)
ax.plot_surface(x, y, image_array,rstride=5, cstride=5, cmap='gray')
plt.title('3D Surface Plot of Grayscale Image')
elev1 = 45
azim1 = 10
ax.view_init(elev=elev1 ,azim=azim1)
plt.show()