# -*- coding: utf-8 -*-
"""lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fG3YWVA6hRazndewnGDHSOIN9kZYLIV-
"""

import cv2

import numpy as np

from matplotlib import pyplot as plt

image=cv2.imread('/content/suga-agust-d-bts-hd-wallpaper-preview (1).jpg')

img=cv2.resize(image,(400,400))
print(img.shape)

def linear(img_linear,a,b):

    for r in range(img_linear.shape[0]):
      for g in range(img_linear.shape[1]):
        for b in range(img_linear.shape[2]):
            k=a*(img_linear[r][g][b])+b
            if k>255:
                img_linear[r][g][b]=255
            elif k<0:
                img_linear[r][g][b]=0
            else:
                img_linear[r][g][b]=int(k)

    return img_linear

ab=[[1,1],[1.5,20],[1.55,30],[1.7,35],[1.8,40],[2,50],[2.5,60],[2.55,65],[3,70],[3.5,75],[3.55,80],[4,85],[4.5,90],[4.55,95],[5,100],[5.5,105],[5.55,110],[6,115],[6.5,120],[6.55,125]]

img_linear=np.copy(img)
temp_img=[]
for i in ab:
    img_linear=np.copy(img)
    img_linear=linear(img_linear,i[0],i[1])
    temp_img.append(img_linear)
for i in reversed(ab):
    img_linear=np.copy(img)
    img_linear=linear(img_linear,i[0],i[1])
    temp_img.append(img_linear)

out = cv2.VideoWriter('/content/lab2.1.1.avi',cv2.VideoWriter_fourcc(*'DIVX'),2, (400,400))
for i in range(len(temp_img)):
    out.write(temp_img[i])

out.release()

